выполняю задание 2
Kolesa-Education/kolesa-upgrade-homework-2 pull request #1
Opened 2022-09-16 17:20 UTC by Azamatds

2022-09-18 05:02 UTC, YerkebulanAben reviewed
Отлично! принимаю твою работу.
Но можешь, если хочешь, попробовать реализовать доп. функционал из требований :"Добавлены другие классы для категории и параметров объявления, возможности объектов расширены, добавлены дополнительные методы." Реализовать отдельный класс,отвечающий за переводы, еще например, чтобы заголовок можно было и на других языках выводить: казахский, английский. Выполнение каких-то из доп. требований даст тебе доп. баллы)

2022-09-18 05:40 UTC, YerkebulanAben requested changes

2022-09-19 09:17 UTC, Azamatds commented on SaleHouse.php
> +        $this->setPrice($this->getPrice()/1000000);
public function getTitle()
    {
        $updPrice = $this->getPrice();
        $updPrice /=1000000;
        return "Продам $this->rooms -комнатный дом за $updPrice млн. тг <br>";
    }

2022-09-19 09:17 UTC, Azamatds commented on RentHouse.php
> +            return "Сдам  $this->rooms -комнатную квартиру за $this->price тг в  месяц <br>";
public function getTitle()
    {
        $trip = "";
        $title = "Сдам %d -комнатную квартиру за %d тг в %s";
        if ($this->getPeriod() == 'month'){
            $trip = "месяц";
        }
        else{
            $trip = "сутки";
        }
        return sprintf($title,$this->getRooms(),$this->getPrice(),$trip)." <br>";
    }

2022-09-19 09:25 UTC, Azamatds commented on home.php
> +include 'House.php';
понял

2022-09-19 10:01 UTC, YerkebulanAben commented on SaleHouse.php
> +        $this->setPrice($this->getPrice()/1000000);
Запушишь плз все что ты тут написал

2022-09-19 14:04 UTC, YerkebulanAben reviewed
Принял дз. Если хочешь можешь как я до этого писал доп. требования выполнить ну и исправить мои комменты)

2022-09-19 14:04 UTC, YerkebulanAben commented on RentHouse.php
> +            $trip = "месяц";
можно просто здесь же и сделать return тем самым не надо будет писать ниже else

2022-09-19 14:04 UTC, YerkebulanAben commented on RentHouse.php
> +        $trip = "";
можно не писать

2022-09-19 14:04 UTC, YerkebulanAben commented on SaleHouse.php
> +        return "Продам $this->rooms -комнатный дом за $updPrice млн. тг <br>";
можно было sprintf() исаользовать

2022-09-22 05:02 UTC, closed without merging