выполняю задание 2
Kolesa-Education/kolesa-upgrade-homework-2 pull request #3
Opened 2022-09-17 08:14 UTC by FishSev

Сделал HW2.
С ООП пришлось немного повозиться, не привычно.

2022-09-19 12:07 UTC, Tazya requested changes
Задание выполнено корректно. Но код плохо читается. Сделал несколько предложений по улучшению кода.
И попробуй для практики сделать интерфейс и объявить там метод, который возвращает заголовок.

2022-09-19 12:07 UTC, Tazya commented on src/Advert_class.php
> +    protected $category;
Неиспользуемое свойство

2022-09-19 12:07 UTC, Tazya commented on src/Advert_class.php
> +            $print_price = (string) ($this->price / 10 ** 6) . " млн. тг";
Можно вынести ($this->price / 10 ** 6) в отдельную переменную, например $formattedPrice и делать возврат сразу без переменной $print_price

`return $formattedPrice . " млн. тг";`
`return $formattedPrice . " тыс. тг";`
`return $formattedPrice . " тг";`

2022-09-19 12:07 UTC, Tazya commented on src/Advert_class.php
> +    protected function set_print_price()
Функция названа так, как будто она устанавливает свойство в объект. А она возвращает форматированную цену

2022-09-19 12:07 UTC, Tazya commented on src/Advert_class.php
> +    protected function set_print_type()
Аналогично, set неподходящий глагол

2022-09-19 12:07 UTC, Tazya commented on src/Advert_class.php
> +            $print_type = "комнатный дом";
здесь и ниже можно выходить из метода сразу `return "комнатный дом";`

2022-09-19 12:07 UTC, Tazya commented on src/index.php
> +        return "Сдам $this->rooms-$print_type за $print_price $print_period" . PHP_EOL . "<br>";
$this->rooms-$print_type сложно воспринимается в интерполяции. Давай [через sprintf() сделаем](https://www.php.net/manual/en/function.sprintf.php)

2022-09-19 12:07 UTC, Tazya commented on src/Advert_class.php
> +abstract class Advert_class
_class можно убрать. И так понятно, что это класс.[ Венгерская нотация ](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BD%D0%B3%D0%B5%D1%80%D1%81%D0%BA%D0%B0%D1%8F_%D0%BD%D0%BE%D1%82%D0%B0%D1%86%D0%B8%D1%8F)чаще вводит путаницу. В Колёсах стараемся её не использовать.

2022-09-19 14:06 UTC, FishSev commented on src/Advert_class.php
> +    protected $category;
Убрал

2022-09-19 14:06 UTC, FishSev commented on src/Advert_class.php
> +            $print_price = (string) ($this->price / 10 ** 6) . " млн. тг";
Сделал

2022-09-19 14:06 UTC, FishSev commented on src/Advert_class.php
> +    protected function set_print_price()
Изменил название на get_formatted_price

2022-09-19 14:07 UTC, FishSev commented on src/Advert_class.php
> +    protected function set_print_type()
Изменил на get_house_type

2022-09-19 14:07 UTC, FishSev commented on src/Advert_class.php
> +            $print_type = "комнатный дом";
отрефакторил

2022-09-19 14:07 UTC, FishSev commented on src/index.php
> +        return "Сдам $this->rooms-$print_type за $print_price $print_period" . PHP_EOL . "<br>";
Реализовал через sprintf()

2022-09-19 14:08 UTC, FishSev commented on src/Advert_class.php
> +abstract class Advert_class
ok. Убрал лишнее

2022-09-20 13:15 UTC, Tazya reviewed
Хорошо, оставил пару некритичных замечаний

2022-09-20 13:15 UTC, Tazya commented on src/Title.php
> +interface Title
Некритично, но не очень подходящее название для интерфейса. Как будто описываем сущность заголовка, а не объявления.
Предлагаю назвать AdvertInterface или какое-то слово обозначающее действие с заголовком, а не сам заголовок

2022-09-20 13:15 UTC, Tazya commented on src/index.php
>  $wrong_advert_arr = array();
array() устарел на много лет. Сейчас используется просто `[]`

И переменные именуются в camelCase
$wrongAdverts

arr - тоже не нужно, это так называемая венгерская нотация. Тип переменной и так понятно что массив.

2022-11-17 12:44 UTC, closed without merging