ВЫполняю второе домашнее задание
Kolesa-Education/kolesa-upgrade-homework-2 pull request #33
Opened 2022-09-19 15:29 UTC by DiasKaipan

2022-09-20 05:10 UTC, AAlekseevich requested changes

2022-09-20 05:10 UTC, AAlekseevich commented on main/class.php
> +abstract class AdvertClass
Class в нейминге класса думаю лишнее и так понятно что это класс

2022-09-20 05:10 UTC, AAlekseevich commented on main/class.php
> +        return $advert_price;
Тут проще на выходе разом конвертировать в строку return (string) ((int) $advertPrice) а выше везде убрать приведение к типу int

Опять же вопрос зачем float если изначальные данные у нас идут как int, из за float дальше ненужное приведение к типу int, лучше думаю изначально получать данные в int

2022-09-20 05:10 UTC, AAlekseevich commented on main/class.php
> +        $price_size = log10($this->price);
Наименование переменных и методов по стандарту осуществляется в camelCase стиле

2022-09-20 05:10 UTC, AAlekseevich commented on main/class.php
> +    protected function price()
Наименование методов должно начинаться с глагола, в данном случае как вариант getPrice

2022-09-20 05:10 UTC, AAlekseevich commented on main/index.php
> +    if (!isset($advert["category"]) || !isset($advert["rooms"]) || !is_numeric($advert["rooms"]) ||
Возможно стоит вынести валидацию в отдельный метод, чтоб избавиться от каши тут

2022-09-20 05:10 UTC, AAlekseevich commented on main/index.php
> +        echo $advert->get_title();
echo $advert->get_title(); можно избавиться от дублирования кода если вынести получение заголовка из условия

2022-09-20 05:18 UTC, DiasKaipan commented
Понял принял. К вечеру поправлю

2022-09-20 05:37 UTC, AAlekseevich commented on main/class.php
> +    protected function price()
А еще лучше методы подготовки данных вынести в некий отдельный хелпер и там это все подготавливать

2022-09-20 06:58 UTC, AAlekseevich commented
Еще момент, желательно чтоб 1 файл = 1 класс, так же вместо include(require) можно использовать автозагрузку

2022-09-20 07:24 UTC, AAlekseevich commented on main/index.php
> +        echo $advert->get_title();
Еще бы желательно вынести метод getTitle() в интерфейс, а не в абстрактный класс. В абстрактном классы в основном пишем методы которые одинаковые в реализации для всех наследников, интерфейсом же мы указываем что необходимо реализовать данный метод, а как уже решайте сами

2022-09-21 13:43 UTC, AAlekseevich approved these changes

2022-09-21 13:43 UTC, AAlekseevich commented on index.php
> +interface getTitle{
Тут скорее тогда интерфейс Title

2022-09-21 13:43 UTC, AAlekseevich commented on index.php
> +    protected $rooms;
Старайся везде указывать типы данных protected int $rooms

2022-09-21 13:47 UTC, closed without merging